config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  devise_for :users
  resources :microposts
  resources :microposts do
    member do
      get :following, :follower_user
    end
  end
  resources :relationships, only: [:create, :destroy, :index, :show]
end

app/views/shared/_error_messages.html.erb
<% if @micropost.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% @micropost.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_micropost_path(@user) %>">
    <strong id="following" class="stat">
      <%= current_user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= follower_user_micropost_path(@user) %>">
    <strong id="follower_user" class="stat">
      <%= current_user.follower_user.count %>
    </strong>
    follower
  </a>
</div>